project_id = "gwyinucaeaayuckvevma"

[functions.trello-guard]
verify_jwt = false

[functions.trello-provisioner]
verify_jwt = false

[functions.cobranca-pdf]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.trello-label-lembrete]
verify_jwt = false
